### ISSUE TITLE
TAG not show in This Report

### ISSUE THREAD

**Issue by hiren00727** [BGmot/zabbix-module-avail-report#2]
Hello BGmot, First of all very thankful to your efforts for the making of this type of logic in Availability Report,

Now issue is that overall report working fine but TAG value in the report are based on host tag not trigger tag.

Hostname is there so we think that if possible replace Tags value from Host tag to Trigger tag.

We will very thankful is it resolved or guide for the same

**Comment by BGmot** [comment]
Hello, I'll work on this. Do you want to just show tags in Zabbix frontend to you want them to be exported to .csv too?

**Comment by hiren00727** [comment]
Thanks for quick reply, if possible kindly export this value in CSV also, because it is vary useful for reporting purpose.
Thanks in Advance...

**Comment by BGmot** [comment]
Please check new version https://github.com/BGmot/zabbix-module-avail-report/tree/v1.02

**Comment by hiren00727** [comment]
Thanks you so much @BGmot, It is working fine. Keep it UP..
